### ISSUE TITLE
Make virtual-dom usable outside haskell-ng

### ISSUE THREAD

**Issue by commandodev** [ocharles/virtual-dom#2]
I've had to roll back to 7.8.4 and the old style haskell packages. I've changed `default.nix` to the old style and moved the existing one to `default-ng.nix` while I fiddle around, but I wondered if there was a way to support both syles somehow?

**Comment by ocharles** [comment]
Maybe we could have `default-7.8.4.nix`, and have `shell.nix` export an object containing `virtual-dom` and `virtual-dom-7.8.4`? You would then be able to do `nix-shell -I ~ -A virtual-dom-7.8.4`.

**Comment by commandodev** [comment]
That looks like a good idea, I'll do that and push you a PR.

**Comment by ocharles** [comment]
I'm not currently using GHCJS so it's unlikely I'll get round to fixing this any time soon. If anyone is still interested in this, I will happily merge a PR.
