### ISSUE TITLE
I can't build it

### ISSUE THREAD

**Issue by laygr** [ocharles/virtual-dom#4]
I tried to build it with: cabal install --ghcjs
I get this error:
src/VirtualDom/Prim.hs:53:27:
    Could not deduce (Eq JSString) arising from a use of ‘==’
    from the context (Applicative f)
      bound by the type signature for
                 _HTMLElement :: Applicative f =>
                                 (HTMLElement -> f HTMLElement) -> HTML -> f HTML
      at src/VirtualDom/Prim.hs:51:17-43
    In the expression: ffiGetVNodeType vNode == "VirtualNode"
    In a stmt of a pattern guard for
                   an equation for ‘_HTMLElement’:
      ffiGetVNodeType vNode == "VirtualNode"
    In an equation for ‘_HTMLElement’:
        _HTMLElement f (HTML vNode)
          | ffiGetVNodeType vNode == "VirtualNode"
          = fmap
              (\ (HTMLElement vNode') -> HTML vNode') (f (HTMLElement vNode))
          | otherwise = pure (HTML vNode)
cabal: Error: some packages failed to install:
virtual-dom-0.1 failed during the building phase. The exception was:
ExitFailure 1

**Comment by ocharles** [comment]
One solution is to update your `ghcjs`. However, relying on the `Eq` instance for `JSString` is questionable, so I can probably use `eqRef` here and get this working on older versions. Thanks for the report!
