### ISSUE TITLE
Add support for SVG

### ISSUE THREAD

**Issue by dimsuz** [ocharles/virtual-dom#7]
Elm-lang has elm-svg, I believe this library is a good candidate to have it in Haskell world :)

Is it something you plan to do? I am not coming with the PR, but I guess it wouldn't be hard even for a novice like me to do this stuff (by following `Html` module)? Or do you have some concerns/issues with svg support?

**Comment by ocharles** [comment]
I'm not currently using GHCJS so it's unlikely I'll get round to fixing this any time soon. If anyone is still interested in this, I will happily merge a PR.
